architectury {
	common(providers.gradleProperty("enabled_platforms").get().split(","))
}

sourceSets.main {
	// Recipes and advancements generated by the Fabric datagen run (see fabric/build.gradle.kts).
	resources.srcDir("src/main/generated")
}

dependencies {
	// Only here for Fabric's @Environment annotations - don't use other Fabric Loader classes in common code.
	implementation("net.fabricmc:fabric-loader:${rootProject.property("fabric_loader_version")}")
}
